FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod ./
COPY go.sum* ./
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 go build -o enqueue-test ./cmd/enqueue-test

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/enqueue-test .

ENV REDIS_ADDR=redis:6379

CMD ["./enqueue-test"]
